/*
 Navicat Premium Data Transfer

 Source Server         : 1
 Source Server Type    : MySQL
 Source Server Version : 50528
 Source Host           : localhost:3306
 Source Schema         : activiti

 Target Server Type    : MySQL
 Target Server Version : 50528
 File Encoding         : 65001

 Date: 10/08/2021 16:48:41
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for s_log
-- ----------------------------
DROP TABLE IF EXISTS `s_log`;
CREATE TABLE `s_log`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `descr` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `operModal` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `host` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ipAddress` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `method` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `params` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `errorMsg` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `operUser` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `type` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '0',
  `deptId` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT 0,
  `browser` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `sys` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 103 CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Compact;

-- ----------------------------
-- Records of s_log
-- ----------------------------
INSERT INTO `s_log` VALUES (23, '增加角色', '角色模板', '127.0.0.1', '获取地址失败', '/activiti/sys/role/add', 'POST', 'org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object \'SRole\' on field \'roleName\': rejected value []; codes [NotEmpty.SRole.roleName,NotEmpty.roleName,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [SRole.roleName,roleName]; arguments []; default message [roleName]]; default message [角色名称不能为空]', '成功', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (24, '增加角色', '角色模板', '127.0.0.1', '获取地址失败', '/activiti/sys/role/add', 'POST', 'org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object \'SRole\' on field \'roleName\': rejected value []; codes [NotEmpty.SRole.roleName,NotEmpty.roleName,NotEmpty.java.lang.String,NotEmpty]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [SRole.roleName,roleName]; arguments []; default message [roleName]]; default message [角色名称不能为空]', '成功', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (25, '角色列表', '角色模块', '127.0.0.1', '获取地址失败', '/activiti/sys/role/add', 'POST', 'org.springframework.validation.BeanPropertyBindingResult: 0 errors', '成功', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (26, '增加角色', '角色模块', '127.0.0.1', '获取地址失败', '/activiti/sys/role/add', 'POST', 'org.springframework.validation.BeanPropertyBindingResult: 0 errors', '角色名称重复', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (27, '增加角色', '角色模块', '127.0.0.1', '获取地址失败', '/activiti/sys/role/add', 'POST', 'org.springframework.validation.BeanPropertyBindingResult: 0 errors', '角色名称重复', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (28, '增加角色', '角色模块', '127.0.0.1', '获取地址失败', '/activiti/sys/role/add', 'POST', 'SRole(roleId=null, roleName=普通人, roleKey=people, status=null, roleSort=null, menuCheckStr=null, deptCheckStr=null, delFlag=null, createby=null, updateby=null, createtime=null, menus=[1, 2])', '角色名称重复', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (29, '增加角色', '角色模块', '127.0.0.1', '获取地址失败', '/activiti/sys/role/add', 'POST', 'SRole(roleId=null, roleName=普通人, roleKey=people, status=null, roleSort=null, menuCheckStr=null, deptCheckStr=null, delFlag=null, createby=null, updateby=null, createtime=null, menus=[1, 2])', '角色名称重复', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (30, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=admin, password=123456, code=KLAL, uuid=752)', '成功', 'admin', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (31, '增加请假', '请假模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/add', 'POST', 'LeaveFormDTO(type=1, leaveform=SLeaveform(id=null, procinstid=, proposerId=, agentId=null, title=123, leavetype=0, leavecontent=0, leavetime=null, expiretime=null, createtime=null, endtime=null, reply=null, status=null, currdate=null))', '成功', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (32, '增加请假', '请假模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/add', 'POST', 'LeaveFormDTO(type=1, leaveform=SLeaveform(id=null, procinstid=, proposerId=, agentId=null, title=123, leavetype=0, leavecontent=0, leavetime=null, expiretime=null, createtime=null, endtime=null, reply=null, status=null, currdate=null))', '成功', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (33, '增加请假', '请假模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/add', 'POST', 'LeaveFormDTO(type=1, leaveform=SLeaveform(id=null, procinstid=, proposerId=, agentId=null, title=123, leavetype=0, leavecontent=0, leavetime=null, expiretime=null, createtime=null, endtime=null, reply=null, status=null, currdate=null))', '成功', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (34, '增加申请', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/add', 'POST', 'LeaveFormDTO(type=1, leaveform=SLeaveform(id=null, procinstid=, proposerId=1, agentId=null, title=123, leavetype=0, leavecontent=0, leavetime=null, expiretime=null, createtime=null, endtime=null, reply=null, status=null, currdate=null))', '\r\n### Error updating database.  Cause: java.sql.SQLException: Field \'agent_Id\' doesn\'t have a default value\r\n### The error may exist in file [D:\\xue\\springboot_activiti\\target\\classes\\mapper\\act\\SLeaveformMapper.xml]\r\n### The error may involve com.example.springboot_activiti.project.act.mapper.SLeaveformMapper.insertSelective-Inline\r\n### The error occurred while setting parameters\r\n### SQL: insert into s_leaveform      ( procInstId,                       proposer_Id,                              title,                       leaveType,                       leaveContent )       values ( ?,                       ?,                              ?,                       ?,                       ? )\r\n### Cause: java.sql.SQLException: Field \'agent_Id\' doesn\'t have a default value\n; Field \'agent_Id\' doesn\'t have a default value; nested exception is java.sql.SQLException: Field \'agent_Id\' doesn\'t have a default value', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (35, '增加申请', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/add', 'POST', 'LeaveFormDTO(type=1, leaveform=SLeaveform(id=1, procinstid=, proposerId=1, agentId=null, title=123, leavetype=0, leavecontent=0, leavetime=null, expiretime=null, createtime=null, endtime=null, reply=null, status=null, currdate=null))', '成功', 'admin', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (36, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveFormDTO(type=null, leaveform=null)', '成功', 'admin', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (37, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=3RRU, uuid=520)', NULL, 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (38, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=3RRU, uuid=520)', '验证码已失效', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (39, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=ZREP, uuid=148)', NULL, 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (40, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=JSUB, uuid=605)', NULL, 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (41, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=MF9G, uuid=946)', NULL, 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (42, '登录功能', '登录模块', '127.0.0.1', '{\"msg\":\"the request over max qps for user ,the accessKey=public\",\"code\":4}', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=8NH2, uuid=743)', NULL, 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (43, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=BFER, uuid=145)', '成功', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (44, '增加申请', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/add', 'POST', 'LeaveFormDTO(type=1, leaveform=SLeaveform(id=2, procinstid=17501, proposerId=2, agentId=null, title=gggggg, leavetype=0, leavecontent=0, leavetime=null, expiretime=null, createtime=null, endtime=null, reply=null, status=null, currdate=null))', '成功', 'people', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (45, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveFormDTO(type=null, leaveform=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (46, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=UUDB, uuid=150)', '成功', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (47, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (48, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=DXPG, uuid=367)', '成功', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (49, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (50, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (51, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (52, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (53, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (54, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (55, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=MVZW, uuid=838)', '成功', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (56, '增加申请', '申请模块', '127.0.0.1', '<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"><html><head><title>302 Found</title></head><body><h1>302 Found</h1><p>The requested resource resides temporarily under a different URI.</p><hr/>Powered by Tengine</body></html>', '/activiti/sleaveform/add', 'POST', 'LeaveFormDTO(type=1, leaveform=SLeaveform(id=3, procinstid=20001, proposerId=2, agentId=null, title=gggggg, leavetype=0, leavecontent=0, leavetime=null, expiretime=null, createtime=null, endtime=null, reply=null, status=null, currdate=null, deptId=null))', '成功', 'people', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (57, '增加申请', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/add', 'POST', 'LeaveFormDTO(type=1, leaveform=SLeaveform(id=4, procinstid=20007, proposerId=2, agentId=null, title=gghjk, leavetype=0, leavecontent=0, leavetime=null, expiretime=null, createtime=null, endtime=null, reply=null, status=null, currdate=null, deptId=null))', '成功', 'people', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (58, '增加申请', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/add', 'POST', 'LeaveFormDTO(type=1, leaveform=SLeaveform(id=5, procinstid=20013, proposerId=2, agentId=null, title=gghjk, leavetype=0, leavecontent=0, leavetime=null, expiretime=null, createtime=null, endtime=null, reply=null, status=null, currdate=null, deptId=4))', '成功', 'people', NULL, 'add', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (59, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (60, '申请列表', '申请模块', '127.0.0.1', '{\"code\":1,\"data\":\"\"}', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (61, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (62, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (63, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (64, '申请提交', '申请模块', '127.0.0.1', '{\"msg\":\"the request over max qps for user ,the accessKey=public\",\"code\":4}', '/activiti/sleaveform/complete', 'POST', 'LeaveCompleteDTO(baseId=null, taskId=15001)', 'Cannot find task with id 15001', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (65, '申请提交', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/complete', 'POST', 'LeaveCompleteDTO(baseId=null, taskId=15005)', '成功', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (66, '申请列表', '申请模块', '127.0.0.1', '<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"><html><head><title>302 Found</title></head><body><h1>302 Found</h1><p>The requested resource resides temporarily under a different URI.</p><hr/>Powered by Tengine</body></html>', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (67, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=qu, password=123456, code=3X9X, uuid=821)', '成功', 'qu', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (68, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (69, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', 'Assignee is null', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (70, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', 'Assignee is null', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (71, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=qu, password=123456, code=NFLZ, uuid=449)', '成功', 'qu', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (72, '申请列表', '申请模块', '127.0.0.1', '{\"code\":1,\"data\":\"\"}', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (73, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (74, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '\r\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\r\n### The error may exist in file [D:\\xue\\springboot_activiti\\target\\classes\\mapper\\act\\SLeaveformMapper.xml]\r\n### The error may involve com.example.springboot_activiti.project.act.mapper.SLeaveformMapper.selectByTask-Inline\r\n### The error occurred while setting parameters\r\n### SQL: select id as \"id\",procInstId as \"procinstid\", proposer_Id as \"proposerId\",title as \"title\",leaveType as \"leaveType\",deptId as \"deptId\"     from s_leaveform     where procInstId = ?                   and area=?,\r\n### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (75, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '\r\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\r\n### The error may exist in file [D:\\xue\\springboot_activiti\\target\\classes\\mapper\\act\\SLeaveformMapper.xml]\r\n### The error may involve com.example.springboot_activiti.project.act.mapper.SLeaveformMapper.selectByTask-Inline\r\n### The error occurred while setting parameters\r\n### SQL: select id as \"id\",procInstId as \"procinstid\", proposer_Id as \"proposerId\",title as \"title\",leaveType as \"leaveType\",deptId as \"deptId\"     from s_leaveform     where procInstId = ?                   and area=?,\r\n### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (76, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '\r\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\r\n### The error may exist in file [D:\\xue\\springboot_activiti\\target\\classes\\mapper\\act\\SLeaveformMapper.xml]\r\n### The error may involve com.example.springboot_activiti.project.act.mapper.SLeaveformMapper.selectByTask-Inline\r\n### The error occurred while setting parameters\r\n### SQL: select id as \"id\",procInstId as \"procinstid\", proposer_Id as \"proposerId\",title as \"title\",leaveType as \"leaveType\",deptId as \"deptId\"     from s_leaveform     where procInstId = ?                   and area=?,\r\n### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (77, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '\r\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\r\n### The error may exist in file [D:\\xue\\springboot_activiti\\target\\classes\\mapper\\act\\SLeaveformMapper.xml]\r\n### The error may involve com.example.springboot_activiti.project.act.mapper.SLeaveformMapper.selectByTask-Inline\r\n### The error occurred while setting parameters\r\n### SQL: select id as \"id\",procInstId as \"procinstid\", proposer_Id as \"proposerId\",title as \"title\",leaveType as \"leaveType\",deptId as \"deptId\",area as \"area\"     from s_leaveform     where procInstId = ?                   and area=?,\r\n### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (78, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (79, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '\r\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\r\n### The error may exist in file [D:\\xue\\springboot_activiti\\target\\classes\\mapper\\act\\SLeaveformMapper.xml]\r\n### The error may involve com.example.springboot_activiti.project.act.mapper.SLeaveformMapper.selectByTask-Inline\r\n### The error occurred while setting parameters\r\n### SQL: select id as \"id\",procInstId as \"procinstid\", proposer_Id as \"proposerId\",title as \"title\",leaveType as \"leaveType\",deptId as \"deptId\",area as \"area\"     from s_leaveform     where procInstId = ?                   and area=?,\r\n### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 6', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (80, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (81, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', 'Assignee is null', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (82, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=people, password=123456, code=VHUG, uuid=585)', '成功', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (83, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'people', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (84, '登录功能', '登录模块', '127.0.0.1', '{\"msg\":\"the request over max qps for user ,the accessKey=public\",\"code\":4}', '/activiti/login', 'POST', 'LoginBody(username=jd, password=123456, code=YT57, uuid=465)', '成功', 'jd', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (85, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'jd', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (86, '申请提交', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/complete', 'POST', 'LeaveCompleteDTO(baseId=null, taskId=20005)', '成功', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (87, '申请提交', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/complete', 'POST', 'LeaveCompleteDTO(baseId=null, taskId=20011)', '成功', 'people', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (88, '申请列表', '申请模块', '127.0.0.1', '{\"msg\":\"the request over max qps for user ,the accessKey=public\",\"code\":4}', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'jd', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (89, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=qu, password=123456, code=9LCF, uuid=689)', '成功', 'qu', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (90, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'qu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (91, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=xwqu, password=123456, code=CV7V, uuid=869)', '成功', 'xwqu', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (92, '申请列表', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'xwqu', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (93, '申请提交', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/complete', 'POST', 'LeaveCompleteDTO(baseId=null, taskId=25002)', '成功', 'xwqu', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (94, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=admin, password=123456, code=VLQC, uuid=181)', '成功', 'admin', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (95, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=admin, password=123456, code=VLQC, uuid=181)', '验证码已失效', 'admin', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (96, '登录功能', '登录模块', '127.0.0.1', '获取地址失败', '/activiti/login', 'POST', 'LoginBody(username=admin, password=123456, code=QWGN, uuid=316)', '成功', 'admin', NULL, 'login', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (97, '申请列表', '申请模块', '127.0.0.1', '{\"msg\":\"the request over max qps for user ,the accessKey=public\",\"code\":4}', '/activiti/sleaveform/list', 'POST', 'LeaveCurrentDTO(baseId=null, userId=null, deptId=null)', '成功', 'admin', NULL, 'list', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (98, '申请历史记录', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/history/20001', 'GET', '20001', '成功', 'admin', NULL, 'history', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (99, '申请历史记录', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/history/20001', 'GET', '20001', '成功', 'admin', NULL, 'history', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (100, '申请历史记录', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/history/20001', 'GET', '20001', '成功', 'admin', NULL, 'history', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (101, '申请历史记录', '申请模块', '127.0.0.1', '获取地址失败', '/activiti/sleaveform/history/20001', 'GET', '20001', '成功', 'admin', NULL, 'history', NULL, 0, NULL, NULL);
INSERT INTO `s_log` VALUES (102, '申请历史记录', '申请模块', '127.0.0.1', 'if(window.IPCallBack) {IPCallBack({\"ip\":\"127.0.0.1\",\"pro\":\"\",\"proCode\":\"999999\",\"city\":\"\",\"cityCode\":\"0\",\"region\":\"\",\"regionCode\":\"0\",\"addr\":\" ������ַ\",\"regionNames\":\"\",\"err\":\"noprovince\"});}', '/activiti/sleaveform/history/20001', 'GET', '20001', '成功', 'admin', NULL, 'history', NULL, 0, NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
